scratch-org-def: config/project-scratch-def.json
  assign-permset: false
#  permset-name: yourpermset
  run-apex-tests: false
  delete-scratch-org: false
  show-scratch-org-url: true
#  open-path: c/YourCustomApp.app
#  data-plans:
#    - ./data/YourCustomObject1__c-plan.json
#    - ./data/YourCustomObject2__c-plan.json

